import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import style from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={style.main}>
        <h1 className={style.title}>Algorithm Visualization</h1>
        <ul className={style['link-list']}>
          <li>
            <Link href='/algorithms/bubble_sort'>Bubble sort</Link>
          </li>
        </ul>
      </div>
    </>
  )
}

export default Home
